-- languages: o dicionario ISO 639-1 que o codigo ja usava e o banco de producao nao tinha.
--
-- O DEFEITO QUE ESTA MIGRATION FECHA
-- ---------------------------------------------------------------------------
-- `movies.original_language` e `tv_shows.original_language` tem FK para
-- `languages.code`. O recorte de idiomas (docs/operations/language-cutdown.md)
-- trocou a lista fechada de tres codigos pelo vocabulario ISO 639-1 inteiro
-- (packages/db/src/language-vocabulary.ts) e passou a gravar o idioma como o
-- TMDB o emite. O guarda que sobrou (`normalizeOriginalLanguage`) so deixa
-- passar codigo que esteja no VOCABULARIO -- e presume que a TABELA tambem o
-- tenha.
--
-- A tabela so recebia o vocabulario pelo seed. Medido em producao em
-- 2026-09-16: `languages` com 3 linhas (en, es, pt-BR). Todo codigo do
-- vocabulario fora dessas tres passa pelo guarda e morre na FK -- inclusive
-- `pt`, `ja` e `ko`, tres dos cinco idiomas que o recorte MANTEM. Na mesma
-- medicao: 648 jobs `sync_details` falhados com P2003 (464 em
-- movies_original_language_fkey, 184 em tv_shows_original_language_fkey).
--
-- POR QUE MIGRATION, E NAO SO SEED
-- ---------------------------------------------------------------------------
-- O mesmo motivo de 20260821130000_api_provider_tmdb_exports: o release de
-- producao roda `prisma migrate deploy` e NAO roda `db:seed`. Um dicionario que
-- so existe no seed conserta banco novo e deixa producao exatamente como esta.
--
-- O QUE ESTA MIGRATION NAO FAZ
-- ---------------------------------------------------------------------------
-- Nao altera schema e nao toca linha existente (ON CONFLICT DO NOTHING): as
-- tres linhas de producao, com os flags de publicacao de `pt-BR`, ficam como
-- estao. Nenhum codigo daqui e idioma publicado -- `is_published` e
-- `index_default` nascem false, sem excecao; quem publica e PUBLISHED_LOCALES.
-- `pt-BR` nao esta aqui porque nao e codigo ISO 639-1: e locale de autoria, e
-- continua vindo do seed.
--
-- As linhas espelham LANGUAGE_VOCABULARY uma a uma (travado por
-- tests/governance/language-vocabulary-migration.test.ts). Codigo novo no
-- vocabulario exige migration nova: o teste reprova ate ela existir.

INSERT INTO "languages" ("code", "name_pt", "name_en", "is_published", "index_default")
VALUES
  ('aa', 'Afar', 'Afar', false, false),
  ('ab', 'Abcazio', 'Abkhazian', false, false),
  ('ae', 'Avestico', 'Avestan', false, false),
  ('af', 'Africaner', 'Afrikaans', false, false),
  ('ak', 'Akan', 'Akan', false, false),
  ('am', 'Amarico', 'Amharic', false, false),
  ('an', 'Aragones', 'Aragonese', false, false),
  ('ar', 'Arabe', 'Arabic', false, false),
  ('as', 'Assames', 'Assamese', false, false),
  ('av', 'Avaro', 'Avaric', false, false),
  ('ay', 'Aimara', 'Aymara', false, false),
  ('az', 'Azerbaijano', 'Azerbaijani', false, false),
  ('ba', 'Bashkir', 'Bashkir', false, false),
  ('be', 'Bielorrusso', 'Belarusian', false, false),
  ('bg', 'Bulgaro', 'Bulgarian', false, false),
  ('bi', 'Bislama', 'Bislama', false, false),
  ('bm', 'Bambara', 'Bambara', false, false),
  ('bn', 'Bengali', 'Bengali', false, false),
  ('bo', 'Tibetano', 'Tibetan', false, false),
  ('br', 'Bretao', 'Breton', false, false),
  ('bs', 'Bosnio', 'Bosnian', false, false),
  ('ca', 'Catalao', 'Catalan', false, false),
  ('ce', 'Checheno', 'Chechen', false, false),
  ('ch', 'Chamorro', 'Chamorro', false, false),
  ('cn', 'Cantones', 'Cantonese', false, false),
  ('co', 'Corso', 'Corsican', false, false),
  ('cr', 'Cree', 'Cree', false, false),
  ('cs', 'Tcheco', 'Czech', false, false),
  ('cu', 'Eslavo eclesiastico', 'Church Slavic', false, false),
  ('cv', 'Chuvache', 'Chuvash', false, false),
  ('cy', 'Gales', 'Welsh', false, false),
  ('da', 'Dinamarques', 'Danish', false, false),
  ('de', 'Alemao', 'German', false, false),
  ('dv', 'Divehi', 'Divehi', false, false),
  ('dz', 'Dzonga', 'Dzongkha', false, false),
  ('ee', 'Ewe', 'Ewe', false, false),
  ('el', 'Grego', 'Greek', false, false),
  ('en', 'Ingles', 'English', false, false),
  ('eo', 'Esperanto', 'Esperanto', false, false),
  ('es', 'Espanhol', 'Spanish', false, false),
  ('et', 'Estoniano', 'Estonian', false, false),
  ('eu', 'Basco', 'Basque', false, false),
  ('fa', 'Persa', 'Persian', false, false),
  ('ff', 'Fula', 'Fulah', false, false),
  ('fi', 'Finlandes', 'Finnish', false, false),
  ('fj', 'Fijiano', 'Fijian', false, false),
  ('fo', 'Feroes', 'Faroese', false, false),
  ('fr', 'Frances', 'French', false, false),
  ('fy', 'Frisio ocidental', 'Western Frisian', false, false),
  ('ga', 'Irlandes', 'Irish', false, false),
  ('gd', 'Gaelico escoces', 'Scottish Gaelic', false, false),
  ('gl', 'Galego', 'Galician', false, false),
  ('gn', 'Guarani', 'Guarani', false, false),
  ('gu', 'Guzerate', 'Gujarati', false, false),
  ('gv', 'Manes', 'Manx', false, false),
  ('ha', 'Hausa', 'Hausa', false, false),
  ('he', 'Hebraico', 'Hebrew', false, false),
  ('hi', 'Hindi', 'Hindi', false, false),
  ('ho', 'Hiri motu', 'Hiri Motu', false, false),
  ('hr', 'Croata', 'Croatian', false, false),
  ('ht', 'Crioulo haitiano', 'Haitian Creole', false, false),
  ('hu', 'Hungaro', 'Hungarian', false, false),
  ('hy', 'Armenio', 'Armenian', false, false),
  ('hz', 'Herero', 'Herero', false, false),
  ('ia', 'Interlingua', 'Interlingua', false, false),
  ('id', 'Indonesio', 'Indonesian', false, false),
  ('ie', 'Interlingue', 'Interlingue', false, false),
  ('ig', 'Igbo', 'Igbo', false, false),
  ('ii', 'Yi de Sichuan', 'Sichuan Yi', false, false),
  ('ik', 'Inupiaque', 'Inupiaq', false, false),
  ('io', 'Ido', 'Ido', false, false),
  ('is', 'Islandes', 'Icelandic', false, false),
  ('it', 'Italiano', 'Italian', false, false),
  ('iu', 'Inuktitut', 'Inuktitut', false, false),
  ('ja', 'Japones', 'Japanese', false, false),
  ('jv', 'Javanes', 'Javanese', false, false),
  ('ka', 'Georgiano', 'Georgian', false, false),
  ('kg', 'Congoles', 'Kongo', false, false),
  ('ki', 'Quicuio', 'Kikuyu', false, false),
  ('kj', 'Kuanyama', 'Kuanyama', false, false),
  ('kk', 'Cazaque', 'Kazakh', false, false),
  ('kl', 'Groenlandes', 'Kalaallisut', false, false),
  ('km', 'Khmer', 'Khmer', false, false),
  ('kn', 'Canares', 'Kannada', false, false),
  ('ko', 'Coreano', 'Korean', false, false),
  ('kr', 'Canuri', 'Kanuri', false, false),
  ('ks', 'Caxemira', 'Kashmiri', false, false),
  ('ku', 'Curdo', 'Kurdish', false, false),
  ('kv', 'Komi', 'Komi', false, false),
  ('kw', 'Cornico', 'Cornish', false, false),
  ('ky', 'Quirguiz', 'Kyrgyz', false, false),
  ('la', 'Latim', 'Latin', false, false),
  ('lb', 'Luxemburgues', 'Luxembourgish', false, false),
  ('lg', 'Luganda', 'Ganda', false, false),
  ('li', 'Limburgues', 'Limburgish', false, false),
  ('ln', 'Lingala', 'Lingala', false, false),
  ('lo', 'Laosiano', 'Lao', false, false),
  ('lt', 'Lituano', 'Lithuanian', false, false),
  ('lu', 'Luba-catanga', 'Luba-Katanga', false, false),
  ('lv', 'Letao', 'Latvian', false, false),
  ('mg', 'Malgaxe', 'Malagasy', false, false),
  ('mh', 'Marshales', 'Marshallese', false, false),
  ('mi', 'Maori', 'Maori', false, false),
  ('mk', 'Macedonio', 'Macedonian', false, false),
  ('ml', 'Malaiala', 'Malayalam', false, false),
  ('mn', 'Mongol', 'Mongolian', false, false),
  ('mr', 'Marata', 'Marathi', false, false),
  ('ms', 'Malaio', 'Malay', false, false),
  ('mt', 'Maltes', 'Maltese', false, false),
  ('my', 'Birmanes', 'Burmese', false, false),
  ('na', 'Nauruano', 'Nauru', false, false),
  ('nb', 'Norueges bokmal', 'Norwegian Bokmal', false, false),
  ('nd', 'Ndebele do norte', 'North Ndebele', false, false),
  ('ne', 'Nepali', 'Nepali', false, false),
  ('ng', 'Ndonga', 'Ndonga', false, false),
  ('nl', 'Holandes', 'Dutch', false, false),
  ('nn', 'Norueges nynorsk', 'Norwegian Nynorsk', false, false),
  ('no', 'Norueges', 'Norwegian', false, false),
  ('nr', 'Ndebele do sul', 'South Ndebele', false, false),
  ('nv', 'Navajo', 'Navajo', false, false),
  ('ny', 'Chichewa', 'Chichewa', false, false),
  ('oc', 'Occitano', 'Occitan', false, false),
  ('oj', 'Ojibwa', 'Ojibwa', false, false),
  ('om', 'Oromo', 'Oromo', false, false),
  ('or', 'Oria', 'Oriya', false, false),
  ('os', 'Osseto', 'Ossetian', false, false),
  ('pa', 'Panjabi', 'Punjabi', false, false),
  ('pi', 'Pali', 'Pali', false, false),
  ('pl', 'Polones', 'Polish', false, false),
  ('ps', 'Pasto', 'Pashto', false, false),
  ('pt', 'Portugues', 'Portuguese', false, false),
  ('qu', 'Quiche', 'Quechua', false, false),
  ('rm', 'Romanche', 'Romansh', false, false),
  ('rn', 'Rundi', 'Rundi', false, false),
  ('ro', 'Romeno', 'Romanian', false, false),
  ('ru', 'Russo', 'Russian', false, false),
  ('rw', 'Quiniaruanda', 'Kinyarwanda', false, false),
  ('sa', 'Sanscrito', 'Sanskrit', false, false),
  ('sc', 'Sardo', 'Sardinian', false, false),
  ('sd', 'Sindi', 'Sindhi', false, false),
  ('se', 'Sami do norte', 'Northern Sami', false, false),
  ('sg', 'Sango', 'Sango', false, false),
  ('sh', 'Servo-croata', 'Serbo-Croatian', false, false),
  ('si', 'Cingales', 'Sinhala', false, false),
  ('sk', 'Eslovaco', 'Slovak', false, false),
  ('sl', 'Esloveno', 'Slovenian', false, false),
  ('sm', 'Samoano', 'Samoan', false, false),
  ('sn', 'Xona', 'Shona', false, false),
  ('so', 'Somali', 'Somali', false, false),
  ('sq', 'Albanes', 'Albanian', false, false),
  ('sr', 'Servio', 'Serbian', false, false),
  ('ss', 'Suazi', 'Swati', false, false),
  ('st', 'Soto do sul', 'Southern Sotho', false, false),
  ('su', 'Sundanes', 'Sundanese', false, false),
  ('sv', 'Sueco', 'Swedish', false, false),
  ('sw', 'Suaili', 'Swahili', false, false),
  ('ta', 'Tamil', 'Tamil', false, false),
  ('te', 'Telugo', 'Telugu', false, false),
  ('tg', 'Tadjique', 'Tajik', false, false),
  ('th', 'Tailandes', 'Thai', false, false),
  ('ti', 'Tigrinia', 'Tigrinya', false, false),
  ('tk', 'Turcomano', 'Turkmen', false, false),
  ('tl', 'Tagalo', 'Tagalog', false, false),
  ('tn', 'Tsuana', 'Tswana', false, false),
  ('to', 'Tonganes', 'Tongan', false, false),
  ('tr', 'Turco', 'Turkish', false, false),
  ('ts', 'Tsonga', 'Tsonga', false, false),
  ('tt', 'Tartaro', 'Tatar', false, false),
  ('tw', 'Twi', 'Twi', false, false),
  ('ty', 'Taitiano', 'Tahitian', false, false),
  ('ug', 'Uigur', 'Uyghur', false, false),
  ('uk', 'Ucraniano', 'Ukrainian', false, false),
  ('ur', 'Urdu', 'Urdu', false, false),
  ('uz', 'Uzbeque', 'Uzbek', false, false),
  ('ve', 'Venda', 'Venda', false, false),
  ('vi', 'Vietnamita', 'Vietnamese', false, false),
  ('vo', 'Volapuque', 'Volapuk', false, false),
  ('wa', 'Valao', 'Walloon', false, false),
  ('wo', 'Uolofe', 'Wolof', false, false),
  ('xh', 'Xhosa', 'Xhosa', false, false),
  ('xx', 'Sem idioma', 'No Language', false, false),
  ('yi', 'Iidiche', 'Yiddish', false, false),
  ('yo', 'Ioruba', 'Yoruba', false, false),
  ('za', 'Zhuang', 'Zhuang', false, false),
  ('zh', 'Chines', 'Chinese', false, false),
  ('zu', 'Zulu', 'Zulu', false, false)
ON CONFLICT ("code") DO NOTHING;
