/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'editorial-users': EditorialUserAuthOperations;
    'service-accounts': ServiceAccountAuthOperations;
  };
  blocks: {};
  collections: {
    'editorial-users': EditorialUser;
    'service-accounts': ServiceAccount;
    authors: Author;
    media: Media;
    articles: Article;
    'publication-outbox': PublicationOutbox;
    'autopublish-quota-counters': AutopublishQuotaCounter;
    'autopublish-quota-usage': AutopublishQuotaUsage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'editorial-users': EditorialUsersSelect<false> | EditorialUsersSelect<true>;
    'service-accounts': ServiceAccountsSelect<false> | ServiceAccountsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'publication-outbox': PublicationOutboxSelect<false> | PublicationOutboxSelect<true>;
    'autopublish-quota-counters': AutopublishQuotaCountersSelect<false> | AutopublishQuotaCountersSelect<true>;
    'autopublish-quota-usage': AutopublishQuotaUsageSelect<false> | AutopublishQuotaUsageSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: EditorialUser | ServiceAccount;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface EditorialUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ServiceAccountAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editorial-users".
 */
export interface EditorialUser {
  id: number;
  displayName: string;
  /**
   * Papel efetivo. Publicacao exige editor_in_chief ou administrator.
   */
  role: 'administrator' | 'editor_in_chief' | 'editor' | 'reviewer' | 'writer';
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'editorial-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-accounts".
 */
export interface ServiceAccount {
  id: number;
  label: string;
  purpose: 'mnscr' | 'internal_tooling';
  active?: boolean | null;
  /**
   * Poderes EXPLICITOS. Um booleano generico de automacao daria ao MNScr o direito de consumir a outbox e ao worker de projecao o direito de criar drafts. Lista vazia = conta sem nenhum poder.
   */
  scopes?: ('draft_ingest' | 'publication_projection' | 'editorial_auto_publish')[] | null;
  /**
   * Nunca registre a chave aqui. A API key vive so no Payload.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'service-accounts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  slug: string;
  bio?: string | null;
  avatar?: (number | null) | Media;
  roleLabel?: string | null;
  publicEmail?: string | null;
  sameAs?: string[] | null;
  /**
   * Autor inativo nao pode ser associado a nova publicacao.
   */
  active?: boolean | null;
  /**
   * Este autor aceita assinar materia publicada AUTOMATICAMENTE pelo pipeline? Nasce desligado.
   */
  automationPublishingAllowed?: boolean | null;
  /**
   * Vazio = sem restricao de tipo. Preenchido = SOMENTE estes tipos podem ser assinados automaticamente.
   */
  allowedAutomationContentTypes?: ('news' | 'feature' | 'guide' | 'list' | 'interview' | 'evergreen')[] | null;
  /**
   * Vazio = sem restricao de secao.
   */
  allowedAutomationSections?: string[] | null;
  /**
   * Teto diario proprio deste autor. Vazio = sem teto proprio (o teto global continua valendo).
   */
  automationDailyLimit?: number | null;
  /**
   * Como este autor aceita ser creditado em publicacao automatica. Vazio = nenhum modo aceito.
   */
  automationAttributionModes?: ('byline' | 'newsroom' | 'assisted')[] | null;
  /**
   * Marque para entidades editoriais como "Redacao Cinerie".
   */
  isOrganization?: boolean | null;
  createdBy?: (number | null) | EditorialUser;
  updatedBy?: (number | null) | EditorialUser;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  credit?: string | null;
  sourceName?: string | null;
  sourceUrl?: string | null;
  rightsHolder?: string | null;
  licenseStatus: 'unknown' | 'pending' | 'approved' | 'restricted' | 'expired' | 'prohibited';
  licenseReference?: string | null;
  licenseExpiresAt?: string | null;
  requiresAttribution?: boolean | null;
  allowedForEditorial?: boolean | null;
  allowedForHero?: boolean | null;
  allowedForSocial?: boolean | null;
  aspectRatio?: string | null;
  focalPoint?: {
    x?: number | null;
    y?: number | null;
  };
  contentHash?: string | null;
  provenanceType: 'external_source' | 'cinerie_catalog' | 'cinerie_editorial' | 'licensed_media' | 'human_input';
  restrictions?: string[] | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  subtitle?: string | null;
  summary?: string | null;
  body?:
    | (
        | {
            /**
             * Âncora deste trecho. Gerada automaticamente.
             */
            blockId: string;
            text: string;
            marks?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            /**
             * De onde veio este bloco. O writer nao e fonte primaria.
             */
            provenance?:
              | {
                  origin:
                    | 'external_source'
                    | 'cinerie_catalog'
                    | 'cinerie_editorial'
                    | 'licensed_media'
                    | 'human_input'
                    | 'inference';
                  ref?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            /**
             * Âncora deste trecho. Gerada automaticamente.
             */
            blockId: string;
            level: '2' | '3' | '4';
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            /**
             * Âncora deste trecho. Gerada automaticamente.
             */
            blockId: string;
            media: number | Media;
            alt: string;
            caption?: string | null;
            credit?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            /**
             * Âncora deste trecho. Gerada automaticamente.
             */
            blockId: string;
            /**
             * O site publica o vídeo como link para o provedor, nunca como player incorporado.
             */
            provider: 'youtube' | 'vimeo' | 'internal';
            externalId?: string | null;
            url?: string | null;
            title?: string | null;
            credit?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            /**
             * Âncora deste trecho. Gerada automaticamente.
             */
            blockId: string;
            /**
             * Só o YouTube vira player. Instagram e X aparecem como cartão com link — o site não carrega script de terceiro.
             */
            provider: 'youtube' | 'instagram' | 'x';
            /**
             * Extraído da URL. É com ele que o site monta o player.
             */
            externalId: string;
            canonicalUrl: string;
            originalUrl: string;
            caption?: string | null;
            authorName?: string | null;
            excerpt?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embed';
          }
        | {
            /**
             * Âncora deste trecho. Gerada automaticamente.
             */
            blockId: string;
            items?:
              | {
                  media: number | Media;
                  alt: string;
                  caption?: string | null;
                  credit?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Posição da primeira imagem, contando do zero. Vazio abre na primeira.
             */
            initialIndex?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            /**
             * Âncora deste trecho. Gerada automaticamente.
             */
            blockId: string;
            /**
             * Desmarcado usa marcadores; marcado numera os itens no site.
             */
            ordered?: boolean | null;
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            /**
             * Âncora deste trecho. Gerada automaticamente.
             */
            blockId: string;
            text: string;
            attribution?: string | null;
            sourceRef?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            /**
             * Âncora deste trecho. Gerada automaticamente.
             */
            blockId: string;
            /**
             * Hoje o site só monta o cartão para filme e série. Os demais tipos são aceitos, mas o cartão não é exibido na matéria publicada.
             */
            entityKind: 'movie' | 'tv' | 'season' | 'episode' | 'person' | 'character' | 'franchise';
            entityId: string;
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'entityCard';
          }
        | {
            /**
             * Âncora deste trecho. Gerada automaticamente.
             */
            blockId: string;
            title: string;
            items?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'factBox';
          }
        | {
            /**
             * Âncora deste trecho. Gerada automaticamente.
             */
            blockId: string;
            articleRefs: string[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'relatedContent';
          }
        | {
            /**
             * Âncora deste trecho. Gerada automaticamente.
             */
            blockId: string;
            sourceRefs: string[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'sourceList';
          }
        | {
            /**
             * Âncora deste trecho. Gerada automaticamente.
             */
            blockId: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'divider';
          }
      )[]
    | null;
  slug?: string | null;
  contentType: 'news' | 'feature' | 'review' | 'guide' | 'list' | 'interview' | 'evergreen';
  /**
   * Só pt-BR é publicado hoje. Inglês e espanhol ficam em rascunho até revisão humana.
   */
  language: 'pt-BR' | 'en' | 'es';
  /**
   * Não bloqueia a publicação, mas matéria sem capa perde espaço nas listas e no compartilhamento.
   */
  heroMedia?: (number | null) | Media;
  /**
   * Ficam vinculadas à matéria para reuso e crédito. Não viram galeria na página: para exibir uma imagem no texto, use o bloco de imagem no corpo.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Obrigatório para publicar: ao menos um autor ativo. Um rascunho pode ficar sem autor.
   */
  authors?: (number | Author)[] | null;
  /**
   * Entre os autores acima, quem encabeça a assinatura pública da matéria.
   */
  primaryAuthor?: (number | null) | Author;
  /**
   * Controle interno de quem toca a matéria. Não aparece no site.
   */
  assignedTo?: (number | null) | EditorialUser;
  /**
   * Ex.: Filmes, Séries, Streaming. Campo livre — não há taxonomia fechada ainda.
   */
  section?: string | null;
  /**
   * Organização da redação. Não são as tags públicas da matéria.
   */
  internalTags?: string[] | null;
  /**
   * O que aparece como título no Google. Cerca de 60 caracteres — acima disso, corta.
   */
  metaTitle?: string | null;
  /**
   * O trecho abaixo do título no resultado. Cerca de 155 caracteres — acima disso, corta.
   */
  metaDescription?: string | null;
  /**
   * Ferramenta interna de foco. Não vira meta keywords nem sai no HTML da página.
   */
  focusKeyphrase?: string | null;
  /**
   * Apoio de pauta. Também não sai no HTML.
   */
  relatedKeyphrases?: string[] | null;
  /**
   * Vocabulário da redação para busca interna.
   */
  editorialKeywords?: string[] | null;
  /**
   * Sugestão. O JSON-LD final é montado pelo site, que hoje só aceita NewsArticle e Article — Review, ItemList e HowTo são ignorados.
   */
  schemaTypeRecommendation?: ('NewsArticle' | 'Article' | 'Review' | 'ItemList' | 'HowTo') | null;
  /**
   * Vai no articleSection do JSON-LD. Costuma repetir a editoria.
   */
  articleSection?: string | null;
  /**
   * Vazio, herda o título para busca; se este também estiver vazio, o título da matéria.
   */
  socialTitle?: string | null;
  /**
   * Vazio, herda a descrição para busca; se esta também estiver vazia, a linha de apoio.
   */
  socialDescription?: string | null;
  /**
   * Vazio, usa a capa. A imagem precisa estar liberada para uso social.
   */
  socialMedia?: (number | null) | Media;
  /**
   * Só para matéria republicada de outra origem. Precisa ser https absoluta, e é ignorada quando a página não indexa.
   */
  canonicalOverride?: string | null;
  /**
   * Marca a matéria como noindex e a mantém fora do sitemap.
   */
  noindex?: boolean | null;
  entityReferences?:
    | {
        entityKind: 'movie' | 'tv' | 'season' | 'episode' | 'person' | 'character' | 'franchise';
        entityId: string;
        relation: 'primary_subject' | 'secondary_subject' | 'mentioned' | 'reviewed' | 'recommended' | 'compared';
        confidence?: number | null;
        /**
         * So um humano marca. A automacao envia sempre false.
         */
        verified?: boolean | null;
        id?: string | null;
      }[]
    | null;
  relatedArticleReferences?: (number | Article)[] | null;
  externalSources?:
    | {
        sourceId: string;
        name: string;
        url: string;
        role: 'primary' | 'secondary' | 'press_release' | 'catalog';
        id?: string | null;
      }[]
    | null;
  claims?:
    | {
        claimId: string;
        text: string;
        origin:
          | 'external_source'
          | 'cinerie_catalog'
          | 'cinerie_editorial'
          | 'licensed_media'
          | 'human_input'
          | 'inference';
        sourceRefs?: string[] | null;
        conflictsWith?: string[] | null;
        id?: string | null;
      }[]
    | null;
  provenanceJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  aiAssisted?: boolean | null;
  blockingErrors?: string[] | null;
  warnings?: string[] | null;
  qaVersion?: string | null;
  qaPassedAt?: string | null;
  /**
   * Em que pé está a matéria. Para avançar ou voltar, use os botões no topo da tela.
   */
  workflowStatus:
    | 'automation_draft'
    | 'draft'
    | 'needs_review'
    | 'in_review'
    | 'changes_requested'
    | 'human_reviewed'
    | 'ready_to_publish'
    | 'published'
    | 'needs_update'
    | 'blocked'
    | 'archived'
    | 'retracted';
  /**
   * Agrupa as transições feitas de uma vez. Vazio quando a matéria avançou passo a passo.
   */
  collapseId?: string | null;
  collapsedAt?: string | null;
  collapsedFrom?: string | null;
  /**
   * Hoje só existe um: publicação direta pelo botão "Publicar".
   */
  collapseReason?: string | null;
  scheduledFor?: string | null;
  /**
   * Carimbada pelo servidor no momento em que a matéria vai ao ar.
   */
  publishedAt?: string | null;
  correctedAt?: string | null;
  /**
   * O que mudou depois de publicada. Fica no registro editorial.
   */
  correctionNote?: string | null;
  /**
   * Obrigatório em retratação: explica por que a matéria saiu do ar.
   */
  retractionReason?: string | null;
  /**
   * Retencao juridica: bloqueia publicacao ate liberacao.
   */
  legalHold?: boolean | null;
  /**
   * Usuario do CMS que criou. Vazio em materia da automacao.
   */
  createdBy?: (number | null) | EditorialUser;
  /**
   * Ultimo usuario do CMS que alterou.
   */
  updatedBy?: (number | null) | EditorialUser;
  /**
   * Usuario do CMS que PUBLICOU. Vazio em autopublicacao.
   */
  publishedBy?: (number | null) | EditorialUser;
  /**
   * Publicada automaticamente pelo pipeline, sem revisao previa.
   */
  autoPublished?: boolean | null;
  automationActorId?: string | null;
  /**
   * Rotulo da conta tecnica no momento da operacao.
   */
  automationActorLabel?: string | null;
  /**
   * Escopos EFETIVAMENTE usados, derivados da credencial. Nunca declarados pelo cliente.
   */
  automationScopesUsed?: string[] | null;
  /**
   * Instante em que o SERVIDOR recebeu o pedido. Distinto de `generatedAt`, que e o relogio do produtor e nao e confiavel para auditoria.
   */
  automationReceivedAt?: string | null;
  /**
   * Chave do pedido. Reenvio identico nao duplica.
   */
  automationIdempotencyKey?: string | null;
  automationSourceRevision?: number | null;
  automationPayloadHash?: string | null;
  automationPipelineVersion?: string | null;
  automationContractVersion?: string | null;
  automationContractName?: string | null;
  automationSchemaHash?: string | null;
  automationAttributionMode?: ('byline' | 'newsroom' | 'assisted') | null;
  automationDraftId?: string | null;
  idempotencyKey?: string | null;
  sourceClusterId?: string | null;
  sourceRevision?: number | null;
  sourcePayloadHash?: string | null;
  draftPayloadHash?: string | null;
  pipelineVersion?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publication-outbox".
 */
export interface PublicationOutbox {
  id: number;
  eventId: string;
  idempotencyKey: string;
  eventType: 'article.published' | 'article.updated' | 'article.unpublished' | 'article.retracted';
  aggregateType: string;
  aggregateId: string;
  aggregateVersion: string;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'pending' | 'processing' | 'processed' | 'failed' | 'dead_letter';
  attempts: number;
  availableAt: string;
  leaseToken?: string | null;
  lockedBy?: string | null;
  lockedAt?: string | null;
  leaseExpiresAt?: string | null;
  processedAt?: string | null;
  errorCode?: string | null;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autopublish-quota-counters".
 */
export interface AutopublishQuotaCounter {
  id: number;
  timeZone: string;
  localDate: string;
  dimensionType: 'global' | 'content_type' | 'section' | 'author' | 'article_update';
  dimensionKey: string;
  currentCount: number;
  /**
   * Teto vigente quando o contador subiu. Um dia auditado precisa saber contra QUE limite ele corria, nao o limite de hoje.
   */
  limitSnapshot: number;
  windowStartUtc: string;
  windowEndUtc: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autopublish-quota-usage".
 */
export interface AutopublishQuotaUsage {
  id: number;
  requestId: string;
  idempotencyKey: string;
  sourceClusterId: string;
  sourceRevision: number;
  articleId?: string | null;
  publicAuthorId: string;
  publicationIntent: 'publish' | 'update';
  localDate: string;
  timeZone: string;
  dimensionsConsumed?: string[] | null;
  consumedAt: string;
  serviceAccountId: string;
  pipelineVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'editorial-users';
        value: number | EditorialUser;
      } | null)
    | ({
        relationTo: 'service-accounts';
        value: number | ServiceAccount;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'publication-outbox';
        value: number | PublicationOutbox;
      } | null)
    | ({
        relationTo: 'autopublish-quota-counters';
        value: number | AutopublishQuotaCounter;
      } | null)
    | ({
        relationTo: 'autopublish-quota-usage';
        value: number | AutopublishQuotaUsage;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'editorial-users';
        value: number | EditorialUser;
      }
    | {
        relationTo: 'service-accounts';
        value: number | ServiceAccount;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'editorial-users';
        value: number | EditorialUser;
      }
    | {
        relationTo: 'service-accounts';
        value: number | ServiceAccount;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editorial-users_select".
 */
export interface EditorialUsersSelect<T extends boolean = true> {
  displayName?: T;
  role?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-accounts_select".
 */
export interface ServiceAccountsSelect<T extends boolean = true> {
  label?: T;
  purpose?: T;
  active?: T;
  scopes?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  avatar?: T;
  roleLabel?: T;
  publicEmail?: T;
  sameAs?: T;
  active?: T;
  automationPublishingAllowed?: T;
  allowedAutomationContentTypes?: T;
  allowedAutomationSections?: T;
  automationDailyLimit?: T;
  automationAttributionModes?: T;
  isOrganization?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  sourceName?: T;
  sourceUrl?: T;
  rightsHolder?: T;
  licenseStatus?: T;
  licenseReference?: T;
  licenseExpiresAt?: T;
  requiresAttribution?: T;
  allowedForEditorial?: T;
  allowedForHero?: T;
  allowedForSocial?: T;
  aspectRatio?: T;
  focalPoint?:
    | T
    | {
        x?: T;
        y?: T;
      };
  contentHash?: T;
  provenanceType?: T;
  restrictions?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  summary?: T;
  body?:
    | T
    | {
        paragraph?:
          | T
          | {
              blockId?: T;
              text?: T;
              marks?: T;
              provenance?:
                | T
                | {
                    origin?: T;
                    ref?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        heading?:
          | T
          | {
              blockId?: T;
              level?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              blockId?: T;
              media?: T;
              alt?: T;
              caption?: T;
              credit?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              blockId?: T;
              provider?: T;
              externalId?: T;
              url?: T;
              title?: T;
              credit?: T;
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              blockId?: T;
              provider?: T;
              externalId?: T;
              canonicalUrl?: T;
              originalUrl?: T;
              caption?: T;
              authorName?: T;
              excerpt?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              blockId?: T;
              items?:
                | T
                | {
                    media?: T;
                    alt?: T;
                    caption?: T;
                    credit?: T;
                    id?: T;
                  };
              initialIndex?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              blockId?: T;
              ordered?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              blockId?: T;
              text?: T;
              attribution?: T;
              sourceRef?: T;
              id?: T;
              blockName?: T;
            };
        entityCard?:
          | T
          | {
              blockId?: T;
              entityKind?: T;
              entityId?: T;
              note?: T;
              id?: T;
              blockName?: T;
            };
        factBox?:
          | T
          | {
              blockId?: T;
              title?: T;
              items?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        relatedContent?:
          | T
          | {
              blockId?: T;
              articleRefs?: T;
              id?: T;
              blockName?: T;
            };
        sourceList?:
          | T
          | {
              blockId?: T;
              sourceRefs?: T;
              id?: T;
              blockName?: T;
            };
        divider?:
          | T
          | {
              blockId?: T;
              id?: T;
              blockName?: T;
            };
      };
  slug?: T;
  contentType?: T;
  language?: T;
  heroMedia?: T;
  gallery?: T;
  authors?: T;
  primaryAuthor?: T;
  assignedTo?: T;
  section?: T;
  internalTags?: T;
  metaTitle?: T;
  metaDescription?: T;
  focusKeyphrase?: T;
  relatedKeyphrases?: T;
  editorialKeywords?: T;
  schemaTypeRecommendation?: T;
  articleSection?: T;
  socialTitle?: T;
  socialDescription?: T;
  socialMedia?: T;
  canonicalOverride?: T;
  noindex?: T;
  entityReferences?:
    | T
    | {
        entityKind?: T;
        entityId?: T;
        relation?: T;
        confidence?: T;
        verified?: T;
        id?: T;
      };
  relatedArticleReferences?: T;
  externalSources?:
    | T
    | {
        sourceId?: T;
        name?: T;
        url?: T;
        role?: T;
        id?: T;
      };
  claims?:
    | T
    | {
        claimId?: T;
        text?: T;
        origin?: T;
        sourceRefs?: T;
        conflictsWith?: T;
        id?: T;
      };
  provenanceJson?: T;
  aiAssisted?: T;
  blockingErrors?: T;
  warnings?: T;
  qaVersion?: T;
  qaPassedAt?: T;
  workflowStatus?: T;
  collapseId?: T;
  collapsedAt?: T;
  collapsedFrom?: T;
  collapseReason?: T;
  scheduledFor?: T;
  publishedAt?: T;
  correctedAt?: T;
  correctionNote?: T;
  retractionReason?: T;
  legalHold?: T;
  createdBy?: T;
  updatedBy?: T;
  publishedBy?: T;
  autoPublished?: T;
  automationActorId?: T;
  automationActorLabel?: T;
  automationScopesUsed?: T;
  automationReceivedAt?: T;
  automationIdempotencyKey?: T;
  automationSourceRevision?: T;
  automationPayloadHash?: T;
  automationPipelineVersion?: T;
  automationContractVersion?: T;
  automationContractName?: T;
  automationSchemaHash?: T;
  automationAttributionMode?: T;
  automationDraftId?: T;
  idempotencyKey?: T;
  sourceClusterId?: T;
  sourceRevision?: T;
  sourcePayloadHash?: T;
  draftPayloadHash?: T;
  pipelineVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publication-outbox_select".
 */
export interface PublicationOutboxSelect<T extends boolean = true> {
  eventId?: T;
  idempotencyKey?: T;
  eventType?: T;
  aggregateType?: T;
  aggregateId?: T;
  aggregateVersion?: T;
  payload?: T;
  status?: T;
  attempts?: T;
  availableAt?: T;
  leaseToken?: T;
  lockedBy?: T;
  lockedAt?: T;
  leaseExpiresAt?: T;
  processedAt?: T;
  errorCode?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autopublish-quota-counters_select".
 */
export interface AutopublishQuotaCountersSelect<T extends boolean = true> {
  timeZone?: T;
  localDate?: T;
  dimensionType?: T;
  dimensionKey?: T;
  currentCount?: T;
  limitSnapshot?: T;
  windowStartUtc?: T;
  windowEndUtc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autopublish-quota-usage_select".
 */
export interface AutopublishQuotaUsageSelect<T extends boolean = true> {
  requestId?: T;
  idempotencyKey?: T;
  sourceClusterId?: T;
  sourceRevision?: T;
  articleId?: T;
  publicAuthorId?: T;
  publicationIntent?: T;
  localDate?: T;
  timeZone?: T;
  dimensionsConsumed?: T;
  consumedAt?: T;
  serviceAccountId?: T;
  pipelineVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}